import pandas as pd
print("Name: Pathan Mohid")
print("Roll No: S102")
print()
df = pd.read_csv(r"D:\mohid\python for data secinece\students (5).csv")
print("Student Dataset:")
print(df)
print("\nFirst 10 Records:")
print(df.head(10))
print("\nNumber of Students:")
print(len(df))
print("\nColumn Names:")
print(df.columns)
print("\nAverage Marks:")
print(df["Marks"].mean())
print("\nAverage Attendance:")
print(df["Attendance"].mean())
