import pandas as pd
print("Name: Pathan Mohid")
print("Roll No: S102")
print()
df = pd.read_csv(r"D:\mohid\python for data secinece\students (5).csv")
print("Name and Marks:")
print(df[["Name", "Marks"]])
print("\nStudents scoring more than 75:")
print(df[df["Marks"] > 75])
print("\nStudents with Attendance above 80%:")
print(df[df["Attendance"] > 80])
print("\nFemale Students:")
print(df[df["Gender"] == "Female"])
print("\nBSc CS Students:")
print(df[df["Course"] == "BSc CS"])
print("\nStudents with Marks > 75 and Attendance > 80%:")
print(df[(df["Marks"] > 75) & (df["Attendance"] > 80)])
