import pandas as pd
print("Name: Pathan Mohid")
print("Roll No: S102")
print()
df = pd.read_csv(r"D:\mohid\python for data secinece\students (5).csv")
print("Marks in Ascending Order:")
print(df.sort_values("Marks"))
print("\nMarks in Descending Order:")
print(df.sort_values("Marks", ascending=False))
print("\nAttendance in Descending Order:")
print(df.sort_values("Attendance", ascending=False))
print("\nTop 5 Students:")
print(df.sort_values("Marks", ascending=False).head(5))
print("\nBottom 3 Students:")
print(df.sort_values("Marks").head(3))
